<?php $e = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); $editing = isset($content['id']); ?>
<section class="admin-page container admin-form-page">
<div class="admin-breadcrumb"><a href="/admin">Dashboard</a><span>/</span><span><?= $editing ? 'Edit project' : 'New project' ?></span></div>
<div class="admin-topbar"><div><p class="admin-kicker">Content workspace</p><h1><?= $e($title) ?></h1><p class="admin-lede">Lengkapi metadata dan isi dalam dua bahasa sebelum dipublikasikan.</p></div><?php if ($editing): ?><span class="status status-<?= $e($content['status']) ?>"><?= $e(ucfirst($content['status'])) ?></span><?php endif; ?></div>
<form class="admin-form" method="post" action="<?= $editing ? '/admin/content/' . (int) $content['id'] . '/edit' : '/admin/content/create' ?>">
    <input type="hidden" name="_csrf" value="<?= $e($csrf) ?>">
    <section class="admin-card"><div class="admin-card-heading"><div><p class="admin-kicker">01 · Identity</p><h2>Project details</h2></div></div><div class="form-grid">
    <label>Slug <span class="field-hint">URL identifier</span><input class="admin-input" name="slug" value="<?= $e((string) $content['slug']) ?>" placeholder="my-project" required></label>
    <label>Project type <select class="admin-input" name="project_type">
            <option value="creative_work"<?= $content['project_type'] === 'creative_work' ? ' selected' : '' ?>>Creative work</option>
            <option value="software_application"<?= $content['project_type'] === 'software_application' ? ' selected' : '' ?>>Software application</option>
        </select></label><label>Title ID <input class="admin-input" name="title_id" value="<?= $e((string) $content['title_id']) ?>" required></label><label>Title EN <input class="admin-input" name="title_en" value="<?= $e((string) $content['title_en']) ?>" required></label><div class="form-field"><span class="field-label">Cover image <span class="field-hint">PNG, JPG, GIF, or WebP · max 2 MB</span></span><div class="cover-upload" data-cover-upload data-upload-url="/admin/upload/cover"><input type="hidden" name="cover_image" value="<?= $e((string) $content['cover_image']) ?>" data-cover-path><label class="upload-dropzone"><span class="upload-icon" aria-hidden="true">↑</span><span><strong data-cover-label><?= $content['cover_image'] ? 'Replace cover image' : 'Choose cover image' ?></strong><small>Click to browse from your device</small></span><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" data-cover-file></label><div class="upload-progress" data-cover-status role="status" aria-live="polite"><?= $content['cover_image'] ? 'Current cover is ready.' : '' ?></div><?php if ($content['cover_image']): ?><img class="cover-preview" data-cover-preview src="/media/<?= $e(ltrim(substr((string) $content['cover_image'], strlen('storage/media/')), '/')) ?>" alt="Current cover image"><?php else: ?><img class="cover-preview is-hidden" data-cover-preview alt="Cover preview"><?php endif; ?></div></div><label class="form-span">Tags <span class="field-hint">Pisahkan dengan koma</span><input class="admin-input" name="tags" value="<?= $e((string) $content['tags']) ?>" placeholder="php, sqlite"></label></div></section>
    <section class="admin-card"><div class="admin-card-heading"><div><p class="admin-kicker">02 · Content</p><h2>Content editor</h2></div><span class="field-hint">Markdown + live preview · ID + English required to publish</span></div><div class="form-grid form-grid-content"><?php foreach (['id' => 'Bahasa Indonesia', 'en' => 'English'] as $languageCode => $languageLabel): ?><div class="markdown-editor" data-markdown-editor><div class="markdown-editor-heading"><label for="content_<?= $languageCode ?>"><?= $languageLabel ?></label><div class="markdown-toolbar" role="toolbar" aria-label="<?= $e($languageLabel) ?> formatting tools"><button type="button" data-markdown-action="heading">H</button><button type="button" data-markdown-action="bold"><strong>B</strong></button><button type="button" data-markdown-action="italic"><em>I</em></button><button type="button" data-markdown-action="list">☷</button><button type="button" data-markdown-action="table">▦</button><button type="button" data-markdown-action="preview">Preview</button></div></div><textarea class="admin-input markdown-input" id="content_<?= $languageCode ?>" name="content_<?= $languageCode ?>" rows="16" placeholder="# Judul project..." data-markdown-input><?= $e((string) $content['content_' . $languageCode]) ?></textarea><div class="markdown-preview content-body" data-markdown-preview hidden><span class="field-hint">Preview</span></div></div><?php endforeach; ?></div></section>
    <div class="form-actions"><a class="button button-secondary" href="/admin">Cancel</a><button class="button button-primary" type="submit">Save draft</button></div>
</form>
<?php if ($editing): ?>
    <section class="admin-card lifecycle-card"><div class="admin-card-heading"><div><p class="admin-kicker">03 · Lifecycle</p><h2>Publishing actions</h2></div></div><div class="lifecycle-actions">
    <?php foreach (['publish' => 'Publish', 'archive' => 'Archive', 'restore-draft' => 'Restore as draft', 'restore-published' => 'Restore as published'] as $action => $label): ?>
        <form method="post" action="/admin/content/<?= (int) $content['id'] ?>/<?= $action ?>" style="display:inline">
            <input type="hidden" name="_csrf" value="<?= $e($csrf) ?>">
            <button class="button button-secondary" type="submit"><?= $e($label) ?></button>
        </form>
    <?php endforeach; ?></div></section>
<?php endif; ?>
</section>
